import type { WorkspaceRecord } from "@/lib/types";

const now = new Date("2026-04-19T09:30:00.000Z");

export const demoWorkspaceSeed: WorkspaceRecord = {
  fund: {
    id: "fund_sequoia_demo",
    name: "Sequoia Demo Fund",
    thesis: "Early-stage B2B SaaS across product-led, workflow, and infrastructure software.",
    stage: ["Seed", "Series A", "Series B"],
    sectors: ["SaaS", "Developer Tools", "AI Infrastructure", "Workflow Software"],
    geography: ["US", "Europe"],
    partnerCount: 4,
    friendlyVcCount: 2,
  },
  companies: [
    {
      id: "company_stripe",
      name: "Stripe",
      domain: "stripe.com",
      sector: "Payments Infrastructure",
      stage: "Late Stage",
      description: "Financial infrastructure powering online businesses.",
      geography: "San Francisco",
      signalState: "hydrated",
      employeeCount: 8500,
      raiseReadiness: 88,
    },
    {
      id: "company_notion",
      name: "Notion",
      domain: "notion.so",
      sector: "Work OS",
      stage: "Series B",
      description: "Collaborative operating system for teams and builders.",
      geography: "San Francisco",
      signalState: "hydrated",
      employeeCount: 420,
      raiseReadiness: 74,
    },
    {
      id: "company_linear",
      name: "Linear",
      domain: "linear.app",
      sector: "Developer Workflow",
      stage: "Series B",
      description: "Issue tracking and product planning for high-velocity teams.",
      geography: "Remote / San Francisco",
      signalState: "hydrated",
      employeeCount: 180,
      raiseReadiness: 81,
    },
  ],
  people: [
    {
      id: "person_karri",
      name: "Karri Saarinen",
      currentTitle: "CEO",
      companyId: "company_linear",
      location: "San Francisco",
      roleType: "Founder",
      trustLevel: "high",
    },
    {
      id: "person_ivan",
      name: "Ivan Zhao",
      currentTitle: "CEO",
      companyId: "company_notion",
      location: "San Francisco",
      roleType: "Founder",
      trustLevel: "medium",
    },
    {
      id: "person_christina",
      name: "Christina Cacioppo",
      currentTitle: "Advisor / Operator",
      location: "San Francisco",
      roleType: "Operator",
      trustLevel: "high",
    },
    {
      id: "person_rita",
      name: "Rita Singh",
      currentTitle: "Partner, a16z",
      location: "Menlo Park",
      roleType: "Friendly VC",
      trustLevel: "medium",
    },
    {
      id: "person_daniel",
      name: "Daniel Gross",
      currentTitle: "Talent Advisor",
      location: "San Francisco",
      roleType: "Advisor",
      trustLevel: "medium",
    },
  ],
  graphNodes: [
    { id: "node_fund", type: "fund", entityId: "fund_sequoia_demo", position: { x: 480, y: 220 } },
    { id: "node_stripe", type: "company", entityId: "company_stripe", position: { x: 210, y: 80 } },
    { id: "node_notion", type: "company", entityId: "company_notion", position: { x: 200, y: 330 } },
    { id: "node_linear", type: "company", entityId: "company_linear", position: { x: 760, y: 110 } },
    { id: "node_karri", type: "founder", entityId: "person_karri", position: { x: 920, y: 240 } },
    { id: "node_ivan", type: "founder", entityId: "person_ivan", position: { x: 80, y: 490 } },
    { id: "node_christina", type: "founder", entityId: "person_christina", position: { x: 560, y: 40 } },
    { id: "node_rita", type: "founder", entityId: "person_rita", position: { x: 830, y: 410 } },
    { id: "node_daniel", type: "founder", entityId: "person_daniel", position: { x: 560, y: 500 } },
  ],
  graphEdges: [
    { id: "edge_fund_stripe", fromNodeId: "node_fund", toNodeId: "node_stripe", edgeType: "portfolio", weight: 1 },
    { id: "edge_fund_notion", fromNodeId: "node_fund", toNodeId: "node_notion", edgeType: "portfolio", weight: 1 },
    { id: "edge_fund_linear", fromNodeId: "node_fund", toNodeId: "node_linear", edgeType: "portfolio", weight: 1 },
    { id: "edge_linear_karri", fromNodeId: "node_linear", toNodeId: "node_karri", edgeType: "network", weight: 0.9 },
    { id: "edge_notion_ivan", fromNodeId: "node_notion", toNodeId: "node_ivan", edgeType: "network", weight: 0.8 },
    { id: "edge_fund_christina", fromNodeId: "node_fund", toNodeId: "node_christina", edgeType: "network", weight: 0.92 },
    { id: "edge_fund_rita", fromNodeId: "node_fund", toNodeId: "node_rita", edgeType: "network", weight: 0.67 },
    { id: "edge_fund_daniel", fromNodeId: "node_fund", toNodeId: "node_daniel", edgeType: "network", weight: 0.71 },
  ],
  signals: [
    {
      id: "signal_linear_launch",
      category: "portfolio",
      entityName: "Linear",
      description: "Hiring velocity accelerated across product engineering and field operations.",
      severity: "medium",
      href: "/dashboard/graph",
      createdAt: new Date(now.getTime() - 1000 * 60 * 50).toISOString(),
    },
    {
      id: "signal_notion_raise",
      category: "raises",
      entityName: "Notion",
      description: "Readiness factors improved after new growth benchmark signals landed.",
      severity: "low",
      href: "/dashboard/graph",
      createdAt: new Date(now.getTime() - 1000 * 60 * 18).toISOString(),
    },
  ],
  asks: [
    {
      id: "ask_seed_customer_intro",
      companyId: "company_linear",
      text: "Warm intro to a Fortune 500 design systems lead evaluating Linear.",
      lane: "CUSTOMER_INTRO",
      urgency: "MEDIUM",
      status: "READY",
      topRouteCandidate: "Christina Cacioppo",
      approvalStatus: "APPROVED",
      createdAt: new Date(now.getTime() - 1000 * 60 * 90).toISOString(),
      routeCandidates: [],
    },
  ],
  raises: [],
  approvals: [],
  executionLog: [
    {
      id: "log_seed_graph",
      event: "Graph initialized",
      description: "Portfolio twins, founders, and network relationships were synced into the operating graph.",
      source: "demo-seed",
      entityHref: "/dashboard/graph",
      occurredAt: new Date(now.getTime() - 1000 * 60 * 80).toISOString(),
    },
  ],
  intelligence: {
    score: 72,
    delta: 6,
    components: [
      { label: "Network Depth", score: 79, delta: 4 },
      { label: "Ask Velocity", score: 68, delta: 8 },
      { label: "Route Accuracy", score: 73, delta: 5 },
      { label: "Outcome Rate", score: 69, delta: 3 },
    ],
    history: [
      { day: "Apr 12", score: 61 },
      { day: "Apr 13", score: 62 },
      { day: "Apr 14", score: 64 },
      { day: "Apr 15", score: 66 },
      { day: "Apr 16", score: 67 },
      { day: "Apr 17", score: 68 },
      { day: "Apr 18", score: 70 },
      { day: "Apr 19", score: 72 },
    ],
  },
  launchedAt: undefined,
};
